spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/nextstep_subway?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: localpw

  jpa:
    hibernate:
      ddl-auto: create